### ISSUE TITLE
BleManager is largely unused.

### ISSUE THREAD

**Issue by ptescher** [mikealbinson/blePlayground#3]
`BleManager` just initializes a `BleScanner` and a `CBCentralManager`. Can't we just skip that and have `BleScanner` initialize the `CBCentralManager` and passing the delegate to itself?

**Comment by mikealbinson** [comment]
We can and in the next push I did, however, for some reason after this change the push button will not recognize bleScanner.centralManager.state for its comparison, so I put in a workaround with the arrayReference object for now
